/**
 * Ornith as an automated Electron acceptance test.
 *
 * Launches the real built application against the repository-owned fake
 * local-inference runtime (never a real llama.cpp), drives the real
 * renderer/preload/IPC/database/orchestrator/`OrnithWorktreeTools` path, and
 * proves the whole bounded tool loop end to end: a project and a task are
 * created through the real IPC surface, the task is put in
 * `READY_FOR_IMPLEMENTATION` with `implementationProvider: 'ornith'` (the
 * specification is seeded directly in the database rather than generated by a
 * live Codex, which this suite must not depend on), the fake runtime is
 * scripted to answer a short, complete `list_files` → `read_file` →
 * `create_file` → `git_diff` → `finish` sequence, and `workflow:implement` is
 * invoked through the real IPC channel.
 *
 * What this proves, all against the real running application:
 *  - execution-provider routing actually reaches Ornith (no silent Claude/
 *    Codex fallback);
 *  - the local runtime must be explicitly started and Healthy first;
 *  - the bounded action sequence actually mutates the real task worktree on
 *    disk, and only the worktree — the original repository is untouched;
 *  - the persisted run and the rendered timeline carry the model's `finish`
 *    summary with no absolute machine path anywhere;
 *  - no commit, remote, or GitHub side effect ever occurs.
 */

import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { createRequire } from 'node:module';
import { DatabaseSync } from 'node:sqlite';
import { _electron as electron, type ElectronApplication, type Locator, type Page } from 'playwright-core';
import { execFileSync } from 'node:child_process';
import { FakeLocalInferenceRuntime, freePort } from '../helpers/fake-local-inference';

const require = createRequire(import.meta.url);
const electronExecutable = require('electron') as string;
const repositoryRoot = resolve(import.meta.dirname, '..', '..');
const builtMain = resolve(repositoryRoot, 'out/main/index.js');
const FAKE_LOCAL_INFERENCE_RUNTIME_PATH = resolve(
  import.meta.dirname,
  '..',
  'fixtures',
  'fake-local-inference-runtime.mjs'
);

function git(cwd: string, args: readonly string[]): void {
  execFileSync('git', args, {
    cwd,
    stdio: 'pipe',
    env: { ...process.env, GIT_TERMINAL_PROMPT: '0', GIT_EDITOR: 'true' }
  });
}

function applicationEnvironment(profile: string): Record<string, string> {
  const env = Object.fromEntries(
    Object.entries(process.env).filter((entry): entry is [string, string] => entry[1] !== undefined)
  );
  env.AGENT_RELAY_DATA_DIR = profile;
  delete env.ELECTRON_RUN_AS_NODE;
  delete env.ELECTRON_RENDERER_URL;
  delete env.AGENT_RELAY_DEVTOOLS;
  return env;
}

async function launch(profile: string, cwd: string): Promise<{ app: ElectronApplication; page: Page }> {
  const app = await electron.launch({
    executablePath: electronExecutable,
    args: ['--disable-gpu', builtMain],
    cwd,
    env: applicationEnvironment(profile),
    timeout: 30_000
  });
  const page = await app.firstWindow();
  page.setDefaultTimeout(15_000);
  return { app, page };
}

function card(page: Page, title: string | RegExp): Locator {
  return page.locator('.card').filter({
    has: page.locator('.card__title', { hasText: title })
  }).first();
}

/** Real IPC, from the renderer's own context — the same seam the app itself uses. */
async function invokeIpc<T = unknown>(page: Page, channel: string, input: unknown): Promise<T> {
  const result = await page.evaluate(
    async ({ channel, input }) => (globalThis as any).agentRelay.invoke(channel, input),
    { channel, input }
  );
  if (!result.ok) {
    throw new Error(`IPC ${channel} failed: ${JSON.stringify(result.error)}`);
  }
  return result.data as T;
}

async function startLocalInference(page: Page, runtimePath: string, port: number): Promise<void> {
  await page.getByRole('button', { name: 'Settings' }).click();
  const settingsCard = card(page, /^Local inference$/);
  await settingsCard.waitFor();
  const saveButton = page.getByRole('button', { name: 'Save settings' });

  await settingsCard.getByLabel(/^Enable local inference/).check();
  await settingsCard.getByRole('combobox', { name: /^Executable/ }).selectOption('explicit_path');
  await settingsCard.getByRole('textbox', { name: 'Executable path', exact: true }).fill(runtimePath);
  await settingsCard.getByLabel(/^Model id/).fill('fake-model');
  await settingsCard.getByRole('combobox', { name: /^Model source/ }).selectOption('runtime_id');
  await settingsCard.getByLabel('Runtime model identifier').fill('fake-model');
  await settingsCard.getByLabel(/^Port/).fill(String(port));
  // The production Ornith path now reserves context for both the chat
  // template and one bounded JSON action. Keep this fixture explicit rather
  // than relying on the generic 4096/4096 manual-inference defaults. 12288,
  // not 8192: the protocol's read_file paging guidance raised the smallest
  // context the immutable prompt fits in from ~7.5K to ~8.3K tokens (the real
  // configuration uses 32768), and this fixture is not a minimal-window test.
  await settingsCard.getByLabel('Context size (tokens)').fill('12288');
  await settingsCard.getByLabel('Default max output tokens').fill('1024');
  await saveButton.click();
  await page.getByText('Settings saved').waitFor();

  const lifecycle = card(page, 'Local inference lifecycle');
  await lifecycle.waitFor();
  await lifecycle.getByRole('button', { name: 'Check capabilities' }).click();
  await expect_(async () => lifecycle.textContent(), (text) => (text ?? '').includes('Executable available: yes'));
  await lifecycle.getByRole('button', { name: /Start runtime/ }).waitFor();
  await lifecycle.getByRole('button', { name: /Start runtime/ }).click();
  // Not a bare `/Healthy/` match: the panel's static "must be Healthy to run
  // a test inference" hint contains that word even while Stopped/Starting, so
  // only the "Current state" line itself is a reliable signal.
  await expect_(async () => lifecycle.textContent(), (text) => /Current state\s*Healthy/.test(text ?? ''));
}

/** A tiny hand-rolled poll, avoiding a dependency on this file's Vitest `expect.poll` typings for boolean predicates. */
async function expect_(read: () => Promise<string | null>, predicate: (text: string | null) => boolean, timeoutMs = 15_000): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  for (;;) {
    const text = await read();
    if (predicate(text)) return;
    if (Date.now() >= deadline) throw new Error(`Condition not met before timeout. Last text: ${text}`);
    await new Promise((r) => setTimeout(r, 200));
  }
}

interface RunRow {
  readonly id: string;
  readonly task_id: string;
  readonly agent: string;
  readonly run_type: string;
  readonly status: string;
  readonly final_message: string | null;
  readonly structured_result: string | null;
  readonly error_message: string | null;
}

function readRuns(profile: string, taskId: string): RunRow[] {
  const db = new DatabaseSync(join(profile, 'agent-relay.sqlite'), { readOnly: true });
  try {
    return db
      .prepare('SELECT id, task_id, agent, run_type, status, final_message, structured_result, error_message FROM runs WHERE task_id = ? ORDER BY started_at ASC')
      .all(taskId) as unknown as RunRow[];
  } finally {
    db.close();
  }
}

describe('Ornith Electron acceptance', () => {
  it('routes an implementation round to Ornith through real IPC/UI, mutates only the worktree, and sanitizes the rendered result', async () => {
    const profile = mkdtempSync(join(tmpdir(), 'agent-relay-ornith-e2e-'));
    const repoDir = mkdtempSync(join(tmpdir(), 'agent-relay-ornith-e2e-repo-'));
    const runtime = new FakeLocalInferenceRuntime().scenario({ health: 'ok' });
    const port = await freePort();

    // A real, minimal Git repository — never touched by anything except the
    // worktree Agent Relay creates from it. `package.json` exists only
    // because Relay's own post-provider verification (`npm run verify`,
    // always run after any provider, Ornith included) requires one; the
    // script itself does nothing.
    git(repoDir, ['init', '-b', 'main']);
    git(repoDir, ['config', 'user.name', 'Ornith E2E Fixture']);
    git(repoDir, ['config', 'user.email', 'fixture@example.invalid']);
    writeFileSync(join(repoDir, 'README.md'), 'Ornith e2e fixture repository.\n', 'utf8');
    writeFileSync(
      join(repoDir, 'package.json'),
      JSON.stringify({ name: 'ornith-e2e-fixture', version: '1.0.0', scripts: { verify: 'node -e "process.exit(0)"' } }),
      'utf8'
    );
    writeFileSync(join(repoDir, '.gitignore'), 'node_modules/\n', 'utf8');
    git(repoDir, ['add', '--', 'README.md', 'package.json', '.gitignore']);
    git(repoDir, ['commit', '-m', 'initial commit']);
    // Not a real install: `worktree-dependencies.ts` only needs *a* directory
    // here to reuse (as a junction) into the worktree it creates — nothing
    // in this suite's scripted Ornith run touches a Node dependency.
    mkdirSync(join(repoDir, 'node_modules'), { recursive: true });
    const originalLog = execFileSync('git', ['log', '--oneline'], { cwd: repoDir }).toString('utf8').trim();

    let running: ElectronApplication | null = null;
    try {
      /* ---------------------------------------------------------------- */
      /* Session 1: configure + start the fake runtime; create the project  */
      /* and task through real IPC.                                        */
      /* ---------------------------------------------------------------- */
      const first = await launch(profile, runtime.path);
      running = first.app;
      const page = first.page;
      await startLocalInference(page, FAKE_LOCAL_INFERENCE_RUNTIME_PATH, port);

      const project = await invokeIpc<{ id: string }>(page, 'projects:addExisting', {
        localPath: repoDir,
        name: 'Ornith E2E Project',
        defaultBranch: 'main'
      });
      const taskTitle = 'Add the Ornith e2e output file';
      const task = await invokeIpc<{ id: string }>(page, 'tasks:create', {
        projectId: project.id,
        title: taskTitle,
        originalRequest: 'Create a small file to prove the bounded Ornith tool loop end to end.',
        implementationProvider: 'ornith'
      });

      /* ---------------------------------------------------------------- */
      /* Seed a specification directly, through a second connection to the */
      /* same live database file: this suite must not depend on a live     */
      /* Codex CLI/API for specification generation, and the app's own     */
      /* repositories re-read on every call, so a quick write here while   */
      /* the app is otherwise idle is visible to it immediately.           */
      /* ---------------------------------------------------------------- */
      const specification = {
        title: taskTitle,
        summary: 'Create a small confirmation file to prove the bounded Ornith tool loop works end to end.',
        assumptions: [],
        acceptanceCriteria: ['A new file exists with the expected content.'],
        constraints: [],
        suggestedTests: [],
        implementationPrompt: 'Create ornith-e2e-output.txt with a short confirmation message, using only the bounded Ornith tool protocol.'
      };
      {
        const db = new DatabaseSync(join(profile, 'agent-relay.sqlite'));
        try {
          const now = new Date().toISOString();
          db.prepare(
            'UPDATE tasks SET status = ?, specification_json = ?, specification_approved_at = ?, updated_at = ? WHERE id = ?'
          ).run('READY_FOR_IMPLEMENTATION', JSON.stringify(specification), now, now, task.id);
        } finally {
          db.close();
        }
      }

      const finishSummary = 'Created ornith-e2e-output.txt via the bounded Ornith tool loop.';
      const sequence = [
        JSON.stringify({ version: 1, action: 'list_files', prefix: '', limit: 20 }),
        JSON.stringify({ version: 1, action: 'read_file', path: 'README.md', offset: 0, limit: 4096 }),
        JSON.stringify({
          version: 1,
          action: 'create_file',
          path: 'ornith-e2e-output.txt',
          content: 'Created by the Ornith e2e acceptance test.\n'
        }),
        JSON.stringify({ version: 1, action: 'git_diff', paths: ['ornith-e2e-output.txt'] }),
        JSON.stringify({ version: 1, action: 'finish', summary: finishSummary })
      ];
      runtime.scenario({ health: 'ok', completionTextSequence: sequence });

      const outcome = await invokeIpc<{ status: string }>(page, 'workflow:implement', { taskId: task.id });
      expect(['READY_FOR_REVIEW', 'CHANGES_REQUESTED', 'FAILED']).toContain(outcome.status);

      /* ---------------------------------------------------------------- */
      /* Database evidence: the run persisted, sanitized, worktree-only.   */
      /* ---------------------------------------------------------------- */
      const runs = readRuns(profile, task.id);
      const ornithRuns = runs.filter((run) => run.agent === 'ornith');
      expect(ornithRuns).toHaveLength(1);
      const ornithRun = ornithRuns[0]!;
      expect(ornithRun.run_type).toBe('implementation');
      // This is the field the model's `finish` summary actually reaches
      // (see `ornith-implementation.ts`) — scoped precisely here, since the
      // *system*-authored `git`-agent row legitimately records the worktree's
      // own path as internal bookkeeping and is not the thing Finding 3 fixed.
      expect(ornithRun.final_message).toBe(finishSummary);
      expect(ornithRun.final_message).not.toContain(profile);
      expect(ornithRun.final_message).not.toContain(repoDir);
      expect(ornithRun.structured_result).toContain('"provider":"ornith"');
      expect(ornithRun.structured_result ?? '').not.toContain(profile);
      expect(ornithRun.structured_result ?? '').not.toContain(repoDir);

      // The mutation landed in a worktree, never in the original repository.
      const afterLog = execFileSync('git', ['log', '--oneline'], { cwd: repoDir }).toString('utf8').trim();
      expect(afterLog).toBe(originalLog);
      expect(() => readFileSync(join(repoDir, 'ornith-e2e-output.txt'))).toThrow();
      expect(execFileSync('git', ['remote'], { cwd: repoDir }).toString('utf8').trim()).toBe('');

      /* ---------------------------------------------------------------- */
      /* Rendered UI: the real timeline shows the exact, sanitized summary. */
      /* (Not a whole-page path scan: the *system* `git`-agent row on this  */
      /* same timeline legitimately renders the worktree's own path as     */
      /* bookkeeping — see the database assertions above for the precise,  */
      /* Finding-3-scoped check on the model-authored text specifically.)  */
      /* ---------------------------------------------------------------- */
      await page.getByRole('button', { name: 'Projects' }).click();
      await page.getByRole('button', { name: /Ornith E2E Project/ }).dblclick();
      await page.getByRole('button', { name: new RegExp(taskTitle) }).dblclick();

      // The newest run (the verification pass) is expanded by default; the
      // Ornith implementation run above it on the spine collapses and must be
      // opened explicitly to reveal its "Outcome" section.
      await page.locator('.relay__head', { hasText: 'Ornith' }).click();
      const finalMessageElement = page.locator('.relay__final', { hasText: finishSummary });
      await finalMessageElement.waitFor();
      expect(await finalMessageElement.textContent()).toBe(finishSummary);

      await running.close();
      running = null;
    } finally {
      if (running) await running.close().catch(() => undefined);
      rmSync(profile, { recursive: true, force: true });
      rmSync(repoDir, { recursive: true, force: true });
      await runtime.cleanup();
    }
  }, 120_000);
});
