/**
 * What `npm run verify` printed under Node v26.10.0 when its script is `node --test` and a test file fails,
 * captured from real runs in disposable repositories (`npm run verify > out 2>&1`, not a terminal). Each is
 * a function of the repository root, because Node prints absolute module locations and only a location
 * inside the worktree can be the files' own. Stack frames are kept as Node printed them.
 *
 * Locations are rebuilt the way Node prints them for the root given — a module location is
 * `pathToFileURL(path).href` (`file:///C:/repo/src/a.js` on Windows, percent-encoded), a plain message
 * names the path with its own separators — never by gluing "file://" to a path, which yields a URL Node
 * would never print for a Windows path.
 */

import { posix, win32 } from 'node:path';
import { pathToFileURL } from 'node:url';

const isWindowsPath = (path: string): boolean => /^[A-Za-z]:[\\/]|^\\\\/.test(path);

/** A path under `root`, spelled by `root`'s own platform. */
export function nodePath(root: string, relative: string): string {
  return isWindowsPath(root) ? win32.join(root, ...relative.split('/')) : posix.join(root, relative);
}

/** The `file:` URL Node prints for a module under `root`. */
export function nodeFileUrl(root: string, relative: string): string {
  return pathToFileURL(nodePath(root, relative), { windows: isWindowsPath(root) }).href;
}

/** A source file declares `whisper` twice (spec reporter). */
export const NODE_TEST_DUPLICATE_DECLARATION_SPEC = (root: string): string => [
  "npm notice run verify",
  "npm notice run node --test --test-reporter=spec",
  `${nodeFileUrl(root, 'src/strings.js')}:3`,
  "export function whisper(s) { return s.toLowerCase() + \"...\"; }",
  "       ^",
  "",
  "SyntaxError: Identifier 'whisper' has already been declared",
  "    at compileSourceTextModule (node:internal/modules/esm/utils:355:16)",
  "    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:93:18)",
  "    at #translate (node:internal/modules/esm/loader:441:20)",
  "    at afterLoad (node:internal/modules/esm/loader:509:29)",
  "    at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:514:12)",
  "    at #getOrCreateModuleJobAfterResolve (node:internal/modules/esm/loader:567:36)",
  "    at afterResolve (node:internal/modules/esm/loader:614:52)",
  "    at ModuleLoader.getOrCreateModuleJob (node:internal/modules/esm/loader:620:12)",
  "    at ModuleJob.syncLink (node:internal/modules/esm/module_job:277:33)",
  "    at ModuleJob.link (node:internal/modules/esm/module_job:389:17)",
  "",
  "Node.js v26.10.0",
  "\u2716 test/strings.test.js (34.48872ms)",
  "\u2139 tests 1",
  "\u2139 suites 0",
  "\u2139 pass 0",
  "\u2139 fail 1",
  "\u2139 cancelled 0",
  "\u2139 skipped 0",
  "\u2139 todo 0",
  "\u2139 duration_ms 46.784908",
  "",
  "\u2716 failing tests:",
  "",
  "test at test/strings.test.js:1:1",
  "\u2716 test/strings.test.js (34.48872ms)",
  "  'test failed'",
].join('\n');

/** The same failure through the tap reporter: every line of the child output prefixed with "# ". */
export const NODE_TEST_DUPLICATE_DECLARATION_TAP = (root: string): string => [
  "npm notice run verify",
  "npm notice run node --test --test-reporter=tap",
  "TAP version 13",
  `# ${nodeFileUrl(root, 'src/strings.js')}:3`,
  "# export function whisper(s) { return s.toLowerCase() + \"...\"; }",
  "#        ^",
  "# SyntaxError: Identifier 'whisper' has already been declared",
  "#     at compileSourceTextModule (node:internal/modules/esm/utils:355:16)",
  "#     at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:93:18)",
  "#     at \\#translate (node:internal/modules/esm/loader:441:20)",
  "#     at afterLoad (node:internal/modules/esm/loader:509:29)",
  "#     at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:514:12)",
  "#     at \\#getOrCreateModuleJobAfterResolve (node:internal/modules/esm/loader:567:36)",
  "#     at afterResolve (node:internal/modules/esm/loader:614:52)",
  "#     at ModuleLoader.getOrCreateModuleJob (node:internal/modules/esm/loader:620:12)",
  "#     at ModuleJob.syncLink (node:internal/modules/esm/module_job:277:33)",
  "#     at ModuleJob.link (node:internal/modules/esm/module_job:389:17)",
  "# Node.js v26.10.0",
  "# Subtest: test/strings.test.js",
  "not ok 1 - test/strings.test.js",
  "  ---",
  "  duration_ms: 46.588011",
  "  type: 'test'",
  `  location: '${nodePath(root, 'test/strings.test.js')}:1:1'`,
  "  failureType: 'testCodeFailure'",
  "  exitCode: 1",
  "  signal: ~",
  "  error: 'test failed'",
  "  code: 'ERR_TEST_FAILURE'",
  "  ...",
  "1..1",
  "# tests 1",
  "# suites 0",
  "# pass 0",
  "# fail 1",
  "# cancelled 0",
  "# skipped 0",
  "# todo 0",
  "# duration_ms 56.362146",
].join('\n');

/** A test imports `whisper`, which the source module does not export (spec reporter). */
export const NODE_TEST_MISSING_EXPORT_SPEC = (root: string): string => [
  "npm notice run verify",
  "npm notice run node --test --test-reporter=spec",
  `${nodeFileUrl(root, 'test/strings.test.js')}:3`,
  "import { shout, whisper } from '../src/strings.js';",
  "                ^^^^^^^",
  "SyntaxError: The requested module '../src/strings.js' does not provide an export named 'whisper'",
  "    at #asyncInstantiate (node:internal/modules/esm/module_job:463:21)",
  "    at async ModuleJob.run (node:internal/modules/esm/module_job:561:5)",
  "    at async node:internal/modules/esm/loader:650:26",
  "    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:105:5)",
  "",
  "Node.js v26.10.0",
  "\u2716 test/strings.test.js (43.718799ms)",
  "\u2139 tests 1",
  "\u2139 suites 0",
  "\u2139 pass 0",
  "\u2139 fail 1",
  "\u2139 cancelled 0",
  "\u2139 skipped 0",
  "\u2139 todo 0",
  "\u2139 duration_ms 56.907095",
  "",
  "\u2716 failing tests:",
  "",
  "test at test/strings.test.js:1:1",
  "\u2716 test/strings.test.js (43.718799ms)",
  "  'test failed'",
].join('\n');

/** The same failure through the tap reporter. */
export const NODE_TEST_MISSING_EXPORT_TAP = (root: string): string => [
  "npm notice run verify",
  "npm notice run node --test --test-reporter=tap",
  "TAP version 13",
  `# ${nodeFileUrl(root, 'test/strings.test.js')}:3`,
  "# import { shout, whisper } from '../src/strings.js';",
  "#                 ^^^^^^^",
  "# SyntaxError: The requested module '../src/strings.js' does not provide an export named 'whisper'",
  "#     at \\#asyncInstantiate (node:internal/modules/esm/module_job:463:21)",
  "#     at async ModuleJob.run (node:internal/modules/esm/module_job:561:5)",
  "#     at async node:internal/modules/esm/loader:650:26",
  "#     at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:105:5)",
  "# Node.js v26.10.0",
  "# Subtest: test/strings.test.js",
  "not ok 1 - test/strings.test.js",
  "  ---",
  "  duration_ms: 31.514341",
  "  type: 'test'",
  `  location: '${nodePath(root, 'test/strings.test.js')}:1:1'`,
  "  failureType: 'testCodeFailure'",
  "  exitCode: 1",
  "  signal: ~",
  "  error: 'test failed'",
  "  code: 'ERR_TEST_FAILURE'",
  "  ...",
  "1..1",
  "# tests 1",
  "# suites 0",
  "# pass 0",
  "# fail 1",
  "# cancelled 0",
  "# skipped 0",
  "# todo 0",
  "# duration_ms 41.051855",
].join('\n');

/** A plain assertion failure (spec reporter). */
export const NODE_TEST_ASSERTION_SPEC = (root: string): string => [
  "npm notice run verify",
  "npm notice run node --test --test-reporter=spec",
  "\u2714 shout (0.513169ms)",
  "\u2716 whisper (1.400106ms)",
  "\u2139 tests 2",
  "\u2139 suites 0",
  "\u2139 pass 1",
  "\u2139 fail 1",
  "\u2139 cancelled 0",
  "\u2139 skipped 0",
  "\u2139 todo 0",
  "\u2139 duration_ms 71.779227",
  "",
  "\u2716 failing tests:",
  "",
  "test at test/strings.test.js:5:1",
  "\u2716 whisper (1.400106ms)",
  "  AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:",
  "  ",
  "  'a' !== 'a...'",
  "  ",
  `      at TestContext.<anonymous> (${nodeFileUrl(root, 'test/strings.test.js')}:5:32)`,
  "      at Test.runInAsyncScope (node:async_hooks:226:14)",
  "      at Test.run (node:internal/test_runner/test:1402:25)",
  "      at Test.processPendingSubtests (node:internal/test_runner/test:974:18)",
  "      at Test.postRun (node:internal/test_runner/test:1542:19)",
  "      at Test.run (node:internal/test_runner/test:1467:12)",
  "      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:387:3) {",
  "    generatedMessage: true,",
  "    code: 'ERR_ASSERTION',",
  "    actual: 'a',",
  "    expected: 'a...',",
  "    operator: 'strictEqual',",
  "    diff: 'simple'",
  "  }",
].join('\n');

/** The duplicate declaration through the dot reporter, which keeps nothing but "test failed". */
export const NODE_TEST_DUPLICATE_DECLARATION_DOT = (_root: string): string => [
  "npm notice run verify",
  "npm notice run node --test --test-reporter=dot",
  "X",
  "",
  "Failed tests:",
  "",
  "\u2716 test/strings.test.js (38.936903ms)",
  "  'test failed'",
].join('\n');

/** A source file imports a package that is not installed: the environment, not the edit. */
export const NODE_TEST_MISSING_PACKAGE_SPEC = (root: string): string => [
  "npm notice run verify",
  "npm notice run node --test --test-reporter=spec",
  "node:internal/modules/package_json_reader:343",
  "  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);",
  "        ^",
  "",
  "Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'left-pad-missing' imported from " + nodePath(root, 'src/strings.js'),
  "    at Object.getPackageJSONURL (node:internal/modules/package_json_reader:343:9)",
  "    at packageResolve (node:internal/modules/esm/resolve:751:25)",
  "    at moduleResolve (node:internal/modules/esm/resolve:840:18)",
  "    at defaultResolve (node:internal/modules/esm/resolve:973:11)",
  "    at #cachedDefaultResolve (node:internal/modules/esm/loader:708:20)",
  "    at #resolveAndMaybeBlockOnLoaderThread (node:internal/modules/esm/loader:728:38)",
  "    at ModuleLoader.resolveSync (node:internal/modules/esm/loader:766:56)",
  "    at #resolve (node:internal/modules/esm/loader:690:17)",
  "    at ModuleLoader.getOrCreateModuleJob (node:internal/modules/esm/loader:610:35)",
  "    at ModuleJob.syncLink (node:internal/modules/esm/module_job:277:33) {",
  "  code: 'ERR_MODULE_NOT_FOUND'",
  "}",
  "",
  "Node.js v26.10.0",
  "\u2716 test/strings.test.js (35.317078ms)",
  "\u2139 tests 1",
  "\u2139 suites 0",
  "\u2139 pass 0",
  "\u2139 fail 1",
  "\u2139 cancelled 0",
  "\u2139 skipped 0",
  "\u2139 todo 0",
  "\u2139 duration_ms 52.17932",
  "",
  "\u2716 failing tests:",
  "",
  "test at test/strings.test.js:1:1",
  "\u2716 test/strings.test.js (35.317078ms)",
  "  'test failed'",
].join('\n');

/** A duplicate declaration inside an installed dependency under node_modules. */
export const NODE_TEST_DEPENDENCY_SYNTAX_ERROR_SPEC = (root: string): string => [
  "npm notice run verify",
  "npm notice run node --test --test-reporter=spec",
  `${nodeFileUrl(root, 'node_modules/helper/index.js')}:2`,
  "export const a = 2;",
  "             ^",
  "",
  "SyntaxError: Identifier 'a' has already been declared",
  "    at compileSourceTextModule (node:internal/modules/esm/utils:355:16)",
  "    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:93:18)",
  "    at #translate (node:internal/modules/esm/loader:441:20)",
  "    at afterLoad (node:internal/modules/esm/loader:509:29)",
  "    at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:514:12)",
  "    at #getOrCreateModuleJobAfterResolve (node:internal/modules/esm/loader:567:36)",
  "    at afterResolve (node:internal/modules/esm/loader:614:52)",
  "    at ModuleLoader.getOrCreateModuleJob (node:internal/modules/esm/loader:620:12)",
  "    at ModuleJob.syncLink (node:internal/modules/esm/module_job:277:33)",
  "    at ModuleJob.link (node:internal/modules/esm/module_job:389:17)",
  "",
  "Node.js v26.10.0",
  "\u2716 test/strings.test.js (38.063688ms)",
  "\u2139 tests 1",
  "\u2139 suites 0",
  "\u2139 pass 0",
  "\u2139 fail 1",
  "\u2139 cancelled 0",
  "\u2139 skipped 0",
  "\u2139 todo 0",
  "\u2139 duration_ms 55.212724",
  "",
  "\u2716 failing tests:",
  "",
  "test at test/strings.test.js:1:1",
  "\u2716 test/strings.test.js (38.063688ms)",
  "  'test failed'",
].join('\n');

/** A missing export requested from a package, not from a project module. */
export const NODE_TEST_DEPENDENCY_MISSING_EXPORT_SPEC = (root: string): string => [
  "npm notice run verify",
  "npm notice run node --test --test-reporter=spec",
  `${nodeFileUrl(root, 'src/strings.js')}:1`,
  "import { b } from \"helper\";",
  "         ^",
  "SyntaxError: The requested module 'helper' does not provide an export named 'b'",
  "    at #asyncInstantiate (node:internal/modules/esm/module_job:463:21)",
  "    at async ModuleJob.run (node:internal/modules/esm/module_job:561:5)",
  "    at async node:internal/modules/esm/loader:650:26",
  "    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:105:5)",
  "",
  "Node.js v26.10.0",
  "\u2716 test/strings.test.js (42.762227ms)",
  "\u2139 tests 1",
  "\u2139 suites 0",
  "\u2139 pass 0",
  "\u2139 fail 1",
  "\u2139 cancelled 0",
  "\u2139 skipped 0",
  "\u2139 todo 0",
  "\u2139 duration_ms 56.337064",
  "",
  "\u2716 failing tests:",
  "",
  "test at test/strings.test.js:1:1",
  "\u2716 test/strings.test.js (42.762227ms)",
  "  'test failed'",
].join('\n');

/** A SyntaxError of another kind in a project file (not one of the two confirmed messages). */
export const NODE_TEST_OTHER_SYNTAX_ERROR_SPEC = (root: string): string => [
  "npm notice run verify",
  "npm notice run node --test --test-reporter=spec",
  `${nodeFileUrl(root, 'src/strings.js')}:2`,
  "export function whisper(s) { return s.toLowerCase( + \"...\"; }",
  "                                                     ^^^^^",
  "",
  "SyntaxError: missing ) after argument list",
  "    at compileSourceTextModule (node:internal/modules/esm/utils:355:16)",
  "    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:93:18)",
  "    at #translate (node:internal/modules/esm/loader:441:20)",
  "    at afterLoad (node:internal/modules/esm/loader:509:29)",
  "    at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:514:12)",
  "    at #getOrCreateModuleJobAfterResolve (node:internal/modules/esm/loader:567:36)",
  "    at afterResolve (node:internal/modules/esm/loader:614:52)",
  "    at ModuleLoader.getOrCreateModuleJob (node:internal/modules/esm/loader:620:12)",
  "    at ModuleJob.syncLink (node:internal/modules/esm/module_job:277:33)",
  "    at ModuleJob.link (node:internal/modules/esm/module_job:389:17)",
  "",
  "Node.js v26.10.0",
  "\u2716 test/strings.test.js (30.505084ms)",
  "\u2139 tests 1",
  "\u2139 suites 0",
  "\u2139 pass 0",
  "\u2139 fail 1",
  "\u2139 cancelled 0",
  "\u2139 skipped 0",
  "\u2139 todo 0",
  "\u2139 duration_ms 42.342273",
  "",
  "\u2716 failing tests:",
  "",
  "test at test/strings.test.js:1:1",
  "\u2716 test/strings.test.js (30.505084ms)",
  "  'test failed'",
].join('\n');
