/**
 * Which checkout a specification describes.
 *
 * Codex writes a specification by reading a repository, and everything after it —
 * the external plan review, triage, a revision, the implementation — works on the
 * task's own branch. They must all be about ONE tree. The project's source checkout
 * is not that tree: it can be on another branch, at another commit, with uncommitted
 * edits, and the task branch is cut from the base branch, not from it. So a
 * specification is generated from a clean checkout of one commit, and that commit is
 * recorded with it here. Every later stage is checked against the record, and a
 * specification whose record is missing, stale or written for another implementer
 * is regenerated by the operator — never approved or implemented as it stands.
 *
 * Pure data and functions, shared by the main process and the renderer.
 */

import { z } from 'zod';
import { implementationProviderSchema, type ImplementationProvider } from './execution-providers';
import { isoDateTime } from './models';

/**
 * Where Codex read the repository:
 * - `task_worktree` — the task's own worktree, which already existed;
 * - `base_commit`   — a temporary, clean, detached checkout of the base branch's commit,
 *                     removed afterwards. The task branch is later cut from that commit.
 */
export const SPECIFICATION_CHECKOUTS = ['task_worktree', 'base_commit'] as const;
export type SpecificationCheckout = (typeof SPECIFICATION_CHECKOUTS)[number];

const commitId = z.string().regex(/^[0-9a-f]{40}([0-9a-f]{24})?$/);

export const specificationGroundingSchema = z
  .object({
    version: z.literal(1),
    checkout: z.enum(SPECIFICATION_CHECKOUTS),
    baseBranch: z.string().min(1).max(255),
    /** The task branch, when the checkout was the task worktree; null for a base-commit checkout. */
    branch: z.string().min(1).max(255).nullable(),
    commit: commitId,
    /** Whether the checkout had no uncommitted changes. A base-commit checkout always does. */
    clean: z.boolean(),
    /** The implementer the specification was written for; its capabilities were in the prompt. */
    implementationProvider: implementationProviderSchema,
    capturedAt: isoDateTime,
    /** Set when a later check found the target no longer matches. Kept, never cleared: regenerate instead. */
    stale: z.object({ detectedAt: isoDateTime, reason: z.string().min(1).max(2_000) }).strict().nullable()
  })
  .strict();
export type SpecificationGrounding = z.infer<typeof specificationGroundingSchema>;

/** A stored record, or null when it is absent or unreadable — both of which mean "not grounded". */
export function parseSpecificationGrounding(json: string | null | undefined): SpecificationGrounding | null {
  if (json === null || json === undefined) return null;
  try {
    const parsed = specificationGroundingSchema.safeParse(JSON.parse(json));
    return parsed.success ? parsed.data : null;
  } catch {
    return null;
  }
}

export type SpecificationGroundingState =
  /** There is no specification to describe. */
  | { readonly kind: 'none' }
  /** A specification with no (readable) record: generated before this existed, or damaged. */
  | { readonly kind: 'ungrounded' }
  /** A later check found the target changed after the specification was generated. */
  | { readonly kind: 'stale'; readonly grounding: SpecificationGrounding; readonly reason: string }
  /**
   * Read from a checkout with uncommitted changes. A commit cannot name that content, so
   * nothing can later prove the tree is still what was read: never trusted, only regenerated.
   */
  | { readonly kind: 'unverifiable'; readonly grounding: SpecificationGrounding }
  /** The task's implementer became Ornith after the specification was written for one that can run commands. */
  | {
      readonly kind: 'provider_changed';
      readonly grounding: SpecificationGrounding;
      readonly recorded: ImplementationProvider;
      readonly current: ImplementationProvider;
    }
  | { readonly kind: 'recorded'; readonly grounding: SpecificationGrounding };

export function specificationGroundingState(task: {
  readonly specificationJson: string | null;
  readonly specificationGroundingJson?: string | null;
  readonly implementationProvider: ImplementationProvider;
}): SpecificationGroundingState {
  if (task.specificationJson === null) return { kind: 'none' };
  const grounding = parseSpecificationGrounding(task.specificationGroundingJson);
  if (grounding === null) return { kind: 'ungrounded' };
  if (grounding.stale !== null) return { kind: 'stale', grounding, reason: grounding.stale.reason };
  if (!grounding.clean) return { kind: 'unverifiable', grounding };
  if (!canCarryOut(grounding.implementationProvider, task.implementationProvider)) {
    return { kind: 'provider_changed', grounding, recorded: grounding.implementationProvider, current: task.implementationProvider };
  }
  return { kind: 'recorded', grounding };
}

/**
 * Whether an implementer can carry out a specification written for another. Claude and
 * Codex can both edit files and run commands, and either can do everything Ornith's
 * actions do; Ornith cannot run a command at all. So only a move TO Ornith from another
 * implementer can leave the specification asking for something impossible.
 */
function canCarryOut(writtenFor: ImplementationProvider, implementer: ImplementationProvider): boolean {
  return implementer !== 'ornith' || writtenFor === 'ornith';
}

const PROVIDER_NAMES: Record<ImplementationProvider, string> = { claude: 'Claude', codex: 'Codex', ornith: 'Ornith' };

/** Why the specification cannot be trusted as it stands, in one sentence; null when it can. */
export function specificationGroundingProblem(state: SpecificationGroundingState): string | null {
  switch (state.kind) {
    case 'none':
    case 'recorded':
      return null;
    case 'ungrounded':
      return 'Agent Relay has no record of which checkout this specification was written against, so its file facts may describe the project folder rather than the task’s branch.';
    case 'stale':
      return `The task’s checkout changed after the specification was generated: ${state.reason}`;
    case 'unverifiable':
      return 'The specification was written from a task worktree with uncommitted changes, which no commit can name, so Agent Relay cannot check that the worktree still holds what was read.';
    case 'provider_changed':
      return `The specification was written for ${PROVIDER_NAMES[state.recorded]}, but the task now uses ${PROVIDER_NAMES[state.current]}, which cannot run commands and may be unable to follow it.`;
  }
}

/** A short commit id for messages. */
export function shortCommit(commit: string): string {
  return commit.slice(0, 12);
}

/** One line naming the target: which checkout, which commit. */
export function describeSpecificationTarget(grounding: SpecificationGrounding): string {
  const where =
    grounding.checkout === 'task_worktree'
      ? `the task worktree on branch ${grounding.branch ?? '(unknown)'}`
      : `a clean checkout of base branch ${grounding.baseBranch}`;
  return `Specification target: ${where} at commit ${grounding.commit}${grounding.clean ? '' : ', with uncommitted changes'}.`;
}
